# Generated by Django 6.0.1 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Project description and details')),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or image', null=True, upload_to='projects/')),
                ('project_link', models.URLField(blank=True, help_text='Link to live project or repository', max_length=500, null=True)),
                ('technologies', models.CharField(blank=True, help_text='Technologies used (comma-separated)', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
