# Generated by Django 6.0.1 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Degree or certification name', max_length=200)),
                ('institute', models.CharField(help_text='Name of educational institution', max_length=200)),
                ('year', models.CharField(help_text='Year or duration (e.g., 2020-2024)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about this education', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Entries',
                'ordering': ['-year'],
            },
        ),
    ]
