# Generated by Django 6.0.1 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('job_title', models.CharField(help_text='Your current job title or role', max_length=100)),
                ('profile_image', models.ImageField(blank=True, help_text='Your profile picture', null=True, upload_to='profile/')),
                ('description', models.TextField(help_text='A brief description about yourself')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bio',
                'verbose_name_plural': 'Bio',
            },
        ),
    ]
