# Generated by Django 6.0.1 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Job title or role', max_length=200)),
                ('organization', models.CharField(help_text='Company or organization name', max_length=200)),
                ('description', models.TextField(help_text='Description of responsibilities and achievements')),
                ('duration', models.CharField(blank=True, help_text='Duration (e.g., Jan 2022 - Present)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience Entries',
                'ordering': ['-id'],
            },
        ),
    ]
